# Generated by Django 4.2.7 on 2023-11-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Borrador", "Borrador"),
                            ("Publicado", "Publicado"),
                            ("Retirado", "Retirado"),
                        ],
                        default="Borrador",
                        max_length=10,
                    ),
                ),
                ("producto", models.CharField(max_length=200)),
                (
                    "fecha_publicacion",
                    models.DateTimeField(verbose_name="Fecha de publicación"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="producto/%Y/%m/%d"
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("descripcion", models.TextField(default="")),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("descuento", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.categoria",
                    ),
                ),
            ],
        ),
    ]
